
---

- name : Multiple condition using when keyword
  hosts : node03
  become : true
  become_user : root
  tasks : 
   - name : execute a command on host server
     command : hostname -s
     when : ansible_distribution == "Ubuntu" and ansible_distribution_major_version != "20"
     register : version_value
   - name : show output
     debug : 
      var : version_value
   - name : another condition
     command : hostname -s
     when : ansible_os_family == "RedHat" or ansible_os_family == "Debian"
     register : version_value2
   - name : show output
     debug : 
      var : version_value2
